/**
 * Type definitions for portfolio frontend.
 *
 * DB-row interfaces are auto-generated by portfolio-backend and synced via CI
 * (see src/types/profile.ts). App-level composites and enums remain hand-written here.
 */

import type {
   Role, TimelineEvent, Tool, Skill, Education, Award, Project, GraphNodeData, GraphLinkData
} from './types/profile';

// Re-export DB-row types for components that import from '../types'
export type {
   Role, TimelineEvent, Tool, Skill, Education, Award, Project, GraphNodeData, GraphLinkData
};

// ── App-level enums and composites (not in DB) ──────────────

/** Event types for timeline rendering */
export type EventType = 'job' | 'promotion' | 'certification' | 'award' | 'education';

/** Contribution level on a project */
export type ContributionRole = 'creator' | 'primary' | 'contributor';

/** Commit tag row — aggregated role distribution data (runtime computed) */
export interface CommitTagData {
   category: 'role';
   value: string;      // e.g. "Analytics Engineer", "LLM-Ops Engineer"
   count: number;     // how many commits had this tag
}

/** Full graph payload for force-directed visualization */
export interface GraphData {
   nodes: GraphNodeData[];
   links: GraphLinkData[];
   roleDistribution: CommitTagData[];    // runtime-computed from tag_summary table
   totalCommits: number;         // aggregate stat
   totalRepos: number;          // aggregate stat
}

/** Complete profile data object — loaded once at app startup via sql.js */
export interface ProfileData {
   roles: Role[];
   events: TimelineEvent[];
   tools: Tool[];
   skills: Skill[];
   education: Education[];
   awards: Award[];
   projects: Project[];
   graph: GraphData;
}
